name: Packer build
on:
  push:
    branches: [main]

jobs:
  build:
    name: packer workflow
    runs-on: ubuntu-latest
    strategy: 
        matrix:
            node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Validate Template
        run: |
          cd packer
          packer init ami.pkr.hcl
          packer validate ami.pkr.hcl
          packer build ami.pkr.hcl